name: spotify_skillbox
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  elementary: ^1.1.0
  provider: ^6.0.2  
  dio: ^4.0.4
  pull_to_refresh: ^2.0.0
  extended_image: ^6.0.1
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  cloud_firestore: ^3.1.8
  audioplayers: ^0.20.1
  flutter_displaymode: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lint: ^1.8.2
  import_sorter: ^4.6.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true


 
